---
- name: update apt cache
  become: yes
  apt:
    update_cache: yes

- name: install aptitude
  apt: 
    pkg: aptitude
  become: yes
  
- name: apt upgrade
  become: yes
  apt:
    upgrade: full

- name: install nodejs apt key
  become: yes
  apt_key: 
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add nodejs apt repo
  become: yes
  apt_repository: 
    repo: 'deb https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main' 
    update_cache: yes

- name: install packages required for shopware.dev setup 1
  become: yes
  apt:
    pkg: ['sudo', 'git', 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'mysql-server']
    state: latest

- name: install packages required for shopware.dev setup 2
  become: yes
  apt: 
    pkg: ['python-mysqldb', 'nodejs', 'chromium-browser', 'default-jre-headless', 'docker.io', 'docker-compose']
    state: latest

- name: sudo apt -y install software-properties-common
  become: yes
  apt:
    pkg: ['software-properties-common']
    state: present

- name: add-apt-repository ppa:ondrej/php
  become: yes
  apt_repository:
    repo: ppa:ondrej/php
    state: present
    update_cache: yes

- name: sudo apt -y install php7.4
  become: yes
  apt:
    pkg: ['php7.4','php7.4-cli','libapache2-mod-php7.4']
    state: present

- name: install php extensions
  become: yes
  apt:
    pkg: ['php7.4-gd', 'php7.4-intl', 'php7.4-iconv', 'php7.4-mbstring', 'php7.4-mysql', 'php7.4-xml', 'php7.4-zip', 'php7.4-json', 'php7.4-curl']
    state: present


- name: Download and install Composer
  shell: curl -sS https://getcomposer.org/installer | php
  args:
    chdir: /usr/src/
    creates: /usr/local/bin/composer
    warn: false
  become: yes
  
- name: Add Composer to global path
  copy: 
    dest: /usr/local/bin/composer
    group: root
    mode: '0755'
    owner: root
    src: /usr/src/composer.phar
    remote_src: yes
  become: yes

- name: add vagrant user to docker group
  user:
    name: vagrant
    groups: docker
    append: yes
  become: yes

- name: add vagrant user to www-data group
  user:
    name: vagrant
    groups: www-data
    append: yes
  become: yes

- name: install apache2
  become: yes
  apt:
    pkg: apache2
    state: latest

- name: change apache run user
  become: yes
  lineinfile:
    dest: "/etc/apache2/envvars"
    regexp: "^export APACHE_RUN_USER="
    line: "export APACHE_RUN_USER=vagrant"
    state: present

- name: change apache run group
  become: yes
  lineinfile:
    dest: "/etc/apache2/envvars"
    regexp: "^export APACHE_RUN_GROUP="
    line: "export APACHE_RUN_GROUP=vagrant"
    state: present

- name: change permissions on /var/lock/apache2
  become: yes
  file:
    path: /var/lock/apache2
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant

- name: change permissions on /var/log/apache2
  become: yes
  file:
    path: /var/log/apache2
    state: directory
    recurse: yes
    owner: vagrant
    group: vagrant
